### ISSUE TITLE
友链插件导致Typecho错误500查询不到数据库

### ISSUE THREAD

**Issue by mapleandtree** [bhaoo/Cuckoo#50]
> 反馈前请确认你的 **CDN或浏览器缓存已经清除**，你没有 **修改相关源代码** ，若你已经确认为项目中的问题，请删除这段文本，继续完成你的反馈

**问题出处：友链插件按照主题教程走了但是依旧无法使用**

这个问题出现在哪个功能上？

**问题结果：导致typecho出现网页错误500**

触发问题后造成了什么效果及影响？

**预期结果：应该受到修复或者给予解决方法**

你觉得这个功能该怎么样？

**问题复现：拉取友链插件下载链接，wget下载到/usr/plugins/Links，回到typecho后台管理启用插件**

你是怎么触发这个问题的？

**配置与环境：ubuntu20.04 Server LTS 1h1g1Gbps Apache2部署的typecho**

- 问题页面：（如果有，请提供一个触发此问题的页面链接）
- PHP 版本：7.4.3
- 数据库类型 / 版本：mysql  Ver 8.0.29-0ubuntu0.20.04.3 for Linux on x86_64 ((Ubuntu))
- Typecho 版本：1.2
- 主题版本：2.0.1（Release 标注的版本号，开发版则写 Dev.）
- 使用的插件：Links（所有使用中的的插件，以便判断兼容性问题）
- 浏览器：edge 版本 101.0.1210.53 (正式版本) (64 位)（浏览器名称及版本号）

**截图（若有）**
![image](https://user-images.githubusercontent.com/89039374/171275741-9b68de39-a5ea-4dc8-88ea-4c4fb1a56264.png)

提供一个此问题触发的截图或报错信息。若没有，则留空。
Table 'typecho_blog.typecho_bloglinks' doesn't exist
Typecho\Db\Adapter\SQLException: Table 'typecho_blog.typecho_bloglinks' doesn't exist in /var/www/html/typecho/var/Typecho/Db/Adapter/Mysqli.php:103
Stack trace:
#0 /var/www/html/typecho/var/Typecho/Db.php(391): Typecho\Db\Adapter\Mysqli->query()
#1 /var/www/html/typecho/var/Typecho/Db.php(424): Typecho\Db->query()
#2 /var/www/html/typecho/usr/plugins/Links/manage-links.php(21): Typecho\Db->fetchAll()
#3 /var/www/html/typecho/admin/extending.php(14): require_once('/var/www/html/t...')
#4 {main}

**补充信息：**

提供尽可能多的相关信息。

**Comment by mapleandtree** [comment]
目前尝试使用Links插件目录下的Mysql.sql导入进数据库内，但是没有任何效果
